# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ai_setting.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QPushButton, QSizePolicy,
    QWidget)
import ms_ai_img_rc

class Ui_Ai_Setting_Window(object):
    def setupUi(self, Ai_Setting_Window):
        if not Ai_Setting_Window.objectName():
            Ai_Setting_Window.setObjectName(u"Ai_Setting_Window")
        Ai_Setting_Window.setWindowModality(Qt.WindowModality.ApplicationModal)
        Ai_Setting_Window.resize(1036, 690)
        Ai_Setting_Window.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        Ai_Setting_Window.setWindowTitle(u"\uc9c0\ub2a5\ud615 \ubd84\uc11d \uc124\uc815")
        icon = QIcon()
        icon.addFile(u":/newPrefix/images/icon2.png", QSize(), QIcon.Normal, QIcon.Off)
        Ai_Setting_Window.setWindowIcon(icon)
        Ai_Setting_Window.setStyleSheet(u"\n"
"background-color: rgb(3, 3, 13);")
        self.ai_setting_info_label = QLabel(Ai_Setting_Window)
        self.ai_setting_info_label.setObjectName(u"ai_setting_info_label")
        self.ai_setting_info_label.setGeometry(QRect(11, 6, 211, 37))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ai_setting_info_label.sizePolicy().hasHeightForWidth())
        self.ai_setting_info_label.setSizePolicy(sizePolicy)
        self.ai_setting_info_label.setMaximumSize(QSize(722, 37))
        font = QFont()
        font.setFamilies([u"NanumBarunGothic"])
        font.setPointSize(14)
        self.ai_setting_info_label.setFont(font)
        self.ai_setting_info_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ai_setting_info_label.setIndent(0)
        self.ai_setting_info_label.setOpenExternalLinks(False)
        self.camera_view_15 = QLabel(Ai_Setting_Window)
        self.camera_view_15.setObjectName(u"camera_view_15")
        self.camera_view_15.setGeometry(QRect(516, 486, 255, 146))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.camera_view_15.sizePolicy().hasHeightForWidth())
        self.camera_view_15.setSizePolicy(sizePolicy1)
        font1 = QFont()
        font1.setFamilies([u"NanumBarunGothic"])
        font1.setPointSize(16)
        self.camera_view_15.setFont(font1)
        self.camera_view_15.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_15.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_15.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_15.setScaledContents(False)
        self.camera_view_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_1 = QLabel(Ai_Setting_Window)
        self.camera_view_1.setObjectName(u"camera_view_1")
        self.camera_view_1.setGeometry(QRect(6, 48, 255, 146))
        sizePolicy1.setHeightForWidth(self.camera_view_1.sizePolicy().hasHeightForWidth())
        self.camera_view_1.setSizePolicy(sizePolicy1)
        self.camera_view_1.setFont(font1)
        self.camera_view_1.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_1.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_1.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_1.setScaledContents(False)
        self.camera_view_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_6 = QLabel(Ai_Setting_Window)
        self.camera_view_6.setObjectName(u"camera_view_6")
        self.camera_view_6.setGeometry(QRect(261, 194, 255, 146))
        sizePolicy1.setHeightForWidth(self.camera_view_6.sizePolicy().hasHeightForWidth())
        self.camera_view_6.setSizePolicy(sizePolicy1)
        self.camera_view_6.setFont(font1)
        self.camera_view_6.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_6.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_6.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_6.setScaledContents(False)
        self.camera_view_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_14 = QLabel(Ai_Setting_Window)
        self.camera_view_14.setObjectName(u"camera_view_14")
        self.camera_view_14.setGeometry(QRect(261, 486, 255, 146))
        sizePolicy1.setHeightForWidth(self.camera_view_14.sizePolicy().hasHeightForWidth())
        self.camera_view_14.setSizePolicy(sizePolicy1)
        self.camera_view_14.setFont(font1)
        self.camera_view_14.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_14.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_14.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_14.setScaledContents(False)
        self.camera_view_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_13 = QLabel(Ai_Setting_Window)
        self.camera_view_13.setObjectName(u"camera_view_13")
        self.camera_view_13.setGeometry(QRect(6, 486, 255, 146))
        sizePolicy1.setHeightForWidth(self.camera_view_13.sizePolicy().hasHeightForWidth())
        self.camera_view_13.setSizePolicy(sizePolicy1)
        self.camera_view_13.setFont(font1)
        self.camera_view_13.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_13.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_13.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_13.setScaledContents(False)
        self.camera_view_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_8 = QLabel(Ai_Setting_Window)
        self.camera_view_8.setObjectName(u"camera_view_8")
        self.camera_view_8.setGeometry(QRect(771, 194, 255, 146))
        sizePolicy1.setHeightForWidth(self.camera_view_8.sizePolicy().hasHeightForWidth())
        self.camera_view_8.setSizePolicy(sizePolicy1)
        self.camera_view_8.setFont(font1)
        self.camera_view_8.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_8.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_8.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_8.setScaledContents(False)
        self.camera_view_8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_16 = QLabel(Ai_Setting_Window)
        self.camera_view_16.setObjectName(u"camera_view_16")
        self.camera_view_16.setGeometry(QRect(771, 486, 255, 146))
        sizePolicy1.setHeightForWidth(self.camera_view_16.sizePolicy().hasHeightForWidth())
        self.camera_view_16.setSizePolicy(sizePolicy1)
        self.camera_view_16.setFont(font1)
        self.camera_view_16.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_16.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_16.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_16.setScaledContents(False)
        self.camera_view_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_11 = QLabel(Ai_Setting_Window)
        self.camera_view_11.setObjectName(u"camera_view_11")
        self.camera_view_11.setGeometry(QRect(516, 340, 255, 146))
        sizePolicy1.setHeightForWidth(self.camera_view_11.sizePolicy().hasHeightForWidth())
        self.camera_view_11.setSizePolicy(sizePolicy1)
        self.camera_view_11.setFont(font1)
        self.camera_view_11.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_11.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_11.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_11.setScaledContents(False)
        self.camera_view_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_4 = QLabel(Ai_Setting_Window)
        self.camera_view_4.setObjectName(u"camera_view_4")
        self.camera_view_4.setGeometry(QRect(771, 48, 255, 146))
        sizePolicy1.setHeightForWidth(self.camera_view_4.sizePolicy().hasHeightForWidth())
        self.camera_view_4.setSizePolicy(sizePolicy1)
        self.camera_view_4.setFont(font1)
        self.camera_view_4.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_4.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_4.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_4.setScaledContents(False)
        self.camera_view_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_3 = QLabel(Ai_Setting_Window)
        self.camera_view_3.setObjectName(u"camera_view_3")
        self.camera_view_3.setGeometry(QRect(516, 48, 255, 146))
        sizePolicy1.setHeightForWidth(self.camera_view_3.sizePolicy().hasHeightForWidth())
        self.camera_view_3.setSizePolicy(sizePolicy1)
        self.camera_view_3.setFont(font1)
        self.camera_view_3.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_3.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_3.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_3.setScaledContents(False)
        self.camera_view_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_5 = QLabel(Ai_Setting_Window)
        self.camera_view_5.setObjectName(u"camera_view_5")
        self.camera_view_5.setGeometry(QRect(6, 194, 255, 146))
        sizePolicy1.setHeightForWidth(self.camera_view_5.sizePolicy().hasHeightForWidth())
        self.camera_view_5.setSizePolicy(sizePolicy1)
        self.camera_view_5.setFont(font1)
        self.camera_view_5.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_5.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_5.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_5.setScaledContents(False)
        self.camera_view_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_2 = QLabel(Ai_Setting_Window)
        self.camera_view_2.setObjectName(u"camera_view_2")
        self.camera_view_2.setGeometry(QRect(261, 48, 255, 146))
        sizePolicy1.setHeightForWidth(self.camera_view_2.sizePolicy().hasHeightForWidth())
        self.camera_view_2.setSizePolicy(sizePolicy1)
        self.camera_view_2.setFont(font1)
        self.camera_view_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_2.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_2.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_2.setScaledContents(False)
        self.camera_view_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_9 = QLabel(Ai_Setting_Window)
        self.camera_view_9.setObjectName(u"camera_view_9")
        self.camera_view_9.setGeometry(QRect(6, 340, 255, 146))
        sizePolicy1.setHeightForWidth(self.camera_view_9.sizePolicy().hasHeightForWidth())
        self.camera_view_9.setSizePolicy(sizePolicy1)
        self.camera_view_9.setFont(font1)
        self.camera_view_9.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_9.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_9.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_9.setScaledContents(False)
        self.camera_view_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_7 = QLabel(Ai_Setting_Window)
        self.camera_view_7.setObjectName(u"camera_view_7")
        self.camera_view_7.setGeometry(QRect(516, 194, 255, 146))
        sizePolicy1.setHeightForWidth(self.camera_view_7.sizePolicy().hasHeightForWidth())
        self.camera_view_7.setSizePolicy(sizePolicy1)
        self.camera_view_7.setFont(font1)
        self.camera_view_7.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_7.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_7.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_7.setScaledContents(False)
        self.camera_view_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_10 = QLabel(Ai_Setting_Window)
        self.camera_view_10.setObjectName(u"camera_view_10")
        self.camera_view_10.setGeometry(QRect(261, 340, 255, 146))
        sizePolicy1.setHeightForWidth(self.camera_view_10.sizePolicy().hasHeightForWidth())
        self.camera_view_10.setSizePolicy(sizePolicy1)
        self.camera_view_10.setFont(font1)
        self.camera_view_10.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_10.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_10.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_10.setScaledContents(False)
        self.camera_view_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_12 = QLabel(Ai_Setting_Window)
        self.camera_view_12.setObjectName(u"camera_view_12")
        self.camera_view_12.setGeometry(QRect(771, 340, 255, 146))
        sizePolicy1.setHeightForWidth(self.camera_view_12.sizePolicy().hasHeightForWidth())
        self.camera_view_12.setSizePolicy(sizePolicy1)
        self.camera_view_12.setFont(font1)
        self.camera_view_12.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_12.setStyleSheet(u"border: 1px solid rgb(119, 118, 123);\n"
"color: rgb(255, 255, 255);")
        self.camera_view_12.setPixmap(QPixmap(u":/newPrefix/images/ico_video_off.svg"))
        self.camera_view_12.setScaledContents(False)
        self.camera_view_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.close_bnt = QPushButton(Ai_Setting_Window)
        self.close_bnt.setObjectName(u"close_bnt")
        self.close_bnt.setGeometry(QRect(958, 640, 71, 41))
        self.close_bnt.setMinimumSize(QSize(71, 41))
        font2 = QFont()
        font2.setFamilies([u"NanumBarunGothic"])
        font2.setPointSize(10)
        self.close_bnt.setFont(font2)
        self.close_bnt.setCursor(QCursor(Qt.PointingHandCursor))
        self.close_bnt.setStyleSheet(u"background-color: rgb(36, 39, 44);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"border: 1px solid rgba(255, 255, 255, 100);\n"
"\n"
"\n"
"")
        self.camera_save_bnt = QPushButton(Ai_Setting_Window)
        self.camera_save_bnt.setObjectName(u"camera_save_bnt")
        self.camera_save_bnt.setGeometry(QRect(880, 640, 71, 41))
        sizePolicy1.setHeightForWidth(self.camera_save_bnt.sizePolicy().hasHeightForWidth())
        self.camera_save_bnt.setSizePolicy(sizePolicy1)
        self.camera_save_bnt.setMinimumSize(QSize(71, 41))
        self.camera_save_bnt.setMaximumSize(QSize(16777210, 41))
        self.camera_save_bnt.setFont(font2)
        self.camera_save_bnt.setCursor(QCursor(Qt.PointingHandCursor))
        self.camera_save_bnt.setStyleSheet(u"\n"
"background-color: qlineargradient(spread:pad, x1:0.244, y1:0.477, x2:1, y2:0.489, stop:0.0845771 rgba(0, 205, 0, 255), stop:1 rgba(56, 188, 56, 255));\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"")
        self.camera_view_ai_check_1 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_1.setObjectName(u"camera_view_ai_check_1")
        self.camera_view_ai_check_1.setGeometry(QRect(230, 159, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_1.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_1.setSizePolicy(sizePolicy1)
        self.camera_view_ai_check_1.setFont(font1)
        self.camera_view_ai_check_1.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_1.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_1.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_1.setScaledContents(True)
        self.camera_view_ai_check_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_name_1 = QLabel(Ai_Setting_Window)
        self.camera_view_name_1.setObjectName(u"camera_view_name_1")
        self.camera_view_name_1.setGeometry(QRect(8, 49, 250, 20))
        sizePolicy.setHeightForWidth(self.camera_view_name_1.sizePolicy().hasHeightForWidth())
        self.camera_view_name_1.setSizePolicy(sizePolicy)
        self.camera_view_name_1.setMaximumSize(QSize(722, 37))
        font3 = QFont()
        font3.setFamilies([u"NanumSquareRound"])
        font3.setPointSize(11)
        font3.setBold(True)
        self.camera_view_name_1.setFont(font3)
        self.camera_view_name_1.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_1.setScaledContents(True)
        self.camera_view_name_1.setMargin(0)
        self.camera_view_name_1.setIndent(15)
        self.camera_view_ai_check_2 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_2.setObjectName(u"camera_view_ai_check_2")
        self.camera_view_ai_check_2.setGeometry(QRect(483, 159, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_2.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_2.setSizePolicy(sizePolicy1)
        self.camera_view_ai_check_2.setFont(font1)
        self.camera_view_ai_check_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_2.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_2.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_2.setScaledContents(True)
        self.camera_view_ai_check_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_name_2 = QLabel(Ai_Setting_Window)
        self.camera_view_name_2.setObjectName(u"camera_view_name_2")
        self.camera_view_name_2.setGeometry(QRect(264, 49, 250, 20))
        sizePolicy.setHeightForWidth(self.camera_view_name_2.sizePolicy().hasHeightForWidth())
        self.camera_view_name_2.setSizePolicy(sizePolicy)
        self.camera_view_name_2.setMaximumSize(QSize(722, 37))
        self.camera_view_name_2.setFont(font3)
        self.camera_view_name_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_2.setMargin(0)
        self.camera_view_name_2.setIndent(15)
        self.camera_view_ai_check_3 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_3.setObjectName(u"camera_view_ai_check_3")
        self.camera_view_ai_check_3.setGeometry(QRect(740, 159, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_3.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_3.setSizePolicy(sizePolicy1)
        font4 = QFont()
        font4.setFamilies([u"NanumBarunGothic"])
        font4.setPointSize(16)
        font4.setBold(False)
        self.camera_view_ai_check_3.setFont(font4)
        self.camera_view_ai_check_3.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_3.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_3.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_3.setScaledContents(True)
        self.camera_view_ai_check_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_name_3 = QLabel(Ai_Setting_Window)
        self.camera_view_name_3.setObjectName(u"camera_view_name_3")
        self.camera_view_name_3.setGeometry(QRect(519, 51, 250, 20))
        sizePolicy.setHeightForWidth(self.camera_view_name_3.sizePolicy().hasHeightForWidth())
        self.camera_view_name_3.setSizePolicy(sizePolicy)
        self.camera_view_name_3.setMaximumSize(QSize(722, 37))
        self.camera_view_name_3.setFont(font3)
        self.camera_view_name_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_3.setMargin(0)
        self.camera_view_name_3.setIndent(15)
        self.camera_view_ai_check_4 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_4.setObjectName(u"camera_view_ai_check_4")
        self.camera_view_ai_check_4.setGeometry(QRect(993, 159, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_4.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_4.setSizePolicy(sizePolicy1)
        self.camera_view_ai_check_4.setFont(font1)
        self.camera_view_ai_check_4.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_4.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_4.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_4.setScaledContents(True)
        self.camera_view_ai_check_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_name_4 = QLabel(Ai_Setting_Window)
        self.camera_view_name_4.setObjectName(u"camera_view_name_4")
        self.camera_view_name_4.setGeometry(QRect(773, 51, 250, 20))
        sizePolicy.setHeightForWidth(self.camera_view_name_4.sizePolicy().hasHeightForWidth())
        self.camera_view_name_4.setSizePolicy(sizePolicy)
        self.camera_view_name_4.setMaximumSize(QSize(722, 37))
        self.camera_view_name_4.setFont(font3)
        self.camera_view_name_4.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_4.setMargin(0)
        self.camera_view_name_4.setIndent(15)
        self.camera_view_ai_check_5 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_5.setObjectName(u"camera_view_ai_check_5")
        self.camera_view_ai_check_5.setGeometry(QRect(229, 305, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_5.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_5.setSizePolicy(sizePolicy1)
        self.camera_view_ai_check_5.setFont(font1)
        self.camera_view_ai_check_5.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_5.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_5.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_5.setScaledContents(True)
        self.camera_view_ai_check_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_name_5 = QLabel(Ai_Setting_Window)
        self.camera_view_name_5.setObjectName(u"camera_view_name_5")
        self.camera_view_name_5.setGeometry(QRect(8, 195, 250, 20))
        sizePolicy.setHeightForWidth(self.camera_view_name_5.sizePolicy().hasHeightForWidth())
        self.camera_view_name_5.setSizePolicy(sizePolicy)
        self.camera_view_name_5.setMaximumSize(QSize(722, 37))
        self.camera_view_name_5.setFont(font3)
        self.camera_view_name_5.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_5.setMargin(0)
        self.camera_view_name_5.setIndent(15)
        self.camera_view_ai_check_6 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_6.setObjectName(u"camera_view_ai_check_6")
        self.camera_view_ai_check_6.setGeometry(QRect(484, 305, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_6.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_6.setSizePolicy(sizePolicy1)
        self.camera_view_ai_check_6.setFont(font1)
        self.camera_view_ai_check_6.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_6.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_6.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_6.setScaledContents(True)
        self.camera_view_ai_check_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_name_6 = QLabel(Ai_Setting_Window)
        self.camera_view_name_6.setObjectName(u"camera_view_name_6")
        self.camera_view_name_6.setGeometry(QRect(264, 195, 250, 20))
        sizePolicy.setHeightForWidth(self.camera_view_name_6.sizePolicy().hasHeightForWidth())
        self.camera_view_name_6.setSizePolicy(sizePolicy)
        self.camera_view_name_6.setMaximumSize(QSize(722, 37))
        self.camera_view_name_6.setFont(font3)
        self.camera_view_name_6.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_6.setMargin(0)
        self.camera_view_name_6.setIndent(15)
        self.camera_view_ai_check_7 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_7.setObjectName(u"camera_view_ai_check_7")
        self.camera_view_ai_check_7.setGeometry(QRect(740, 305, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_7.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_7.setSizePolicy(sizePolicy1)
        self.camera_view_ai_check_7.setFont(font1)
        self.camera_view_ai_check_7.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_7.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_7.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_7.setScaledContents(True)
        self.camera_view_ai_check_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_name_7 = QLabel(Ai_Setting_Window)
        self.camera_view_name_7.setObjectName(u"camera_view_name_7")
        self.camera_view_name_7.setGeometry(QRect(519, 195, 250, 20))
        sizePolicy.setHeightForWidth(self.camera_view_name_7.sizePolicy().hasHeightForWidth())
        self.camera_view_name_7.setSizePolicy(sizePolicy)
        self.camera_view_name_7.setMaximumSize(QSize(722, 37))
        self.camera_view_name_7.setFont(font3)
        self.camera_view_name_7.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_7.setMargin(0)
        self.camera_view_name_7.setIndent(15)
        self.camera_view_ai_check_8 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_8.setObjectName(u"camera_view_ai_check_8")
        self.camera_view_ai_check_8.setGeometry(QRect(993, 305, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_8.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_8.setSizePolicy(sizePolicy1)
        self.camera_view_ai_check_8.setFont(font1)
        self.camera_view_ai_check_8.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_8.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_8.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_8.setScaledContents(True)
        self.camera_view_ai_check_8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_name_8 = QLabel(Ai_Setting_Window)
        self.camera_view_name_8.setObjectName(u"camera_view_name_8")
        self.camera_view_name_8.setGeometry(QRect(773, 195, 250, 20))
        sizePolicy.setHeightForWidth(self.camera_view_name_8.sizePolicy().hasHeightForWidth())
        self.camera_view_name_8.setSizePolicy(sizePolicy)
        self.camera_view_name_8.setMaximumSize(QSize(722, 37))
        self.camera_view_name_8.setFont(font3)
        self.camera_view_name_8.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_8.setMargin(0)
        self.camera_view_name_8.setIndent(15)
        self.camera_view_ai_check_9 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_9.setObjectName(u"camera_view_ai_check_9")
        self.camera_view_ai_check_9.setGeometry(QRect(228, 451, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_9.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_9.setSizePolicy(sizePolicy1)
        self.camera_view_ai_check_9.setFont(font1)
        self.camera_view_ai_check_9.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_9.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_9.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_9.setScaledContents(True)
        self.camera_view_ai_check_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_name_9 = QLabel(Ai_Setting_Window)
        self.camera_view_name_9.setObjectName(u"camera_view_name_9")
        self.camera_view_name_9.setGeometry(QRect(8, 341, 250, 20))
        sizePolicy.setHeightForWidth(self.camera_view_name_9.sizePolicy().hasHeightForWidth())
        self.camera_view_name_9.setSizePolicy(sizePolicy)
        self.camera_view_name_9.setMaximumSize(QSize(722, 37))
        self.camera_view_name_9.setFont(font3)
        self.camera_view_name_9.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_9.setMargin(0)
        self.camera_view_name_9.setIndent(15)
        self.camera_view_ai_check_10 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_10.setObjectName(u"camera_view_ai_check_10")
        self.camera_view_ai_check_10.setGeometry(QRect(486, 451, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_10.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_10.setSizePolicy(sizePolicy1)
        self.camera_view_ai_check_10.setFont(font1)
        self.camera_view_ai_check_10.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_10.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_10.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_10.setScaledContents(True)
        self.camera_view_ai_check_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_name_10 = QLabel(Ai_Setting_Window)
        self.camera_view_name_10.setObjectName(u"camera_view_name_10")
        self.camera_view_name_10.setGeometry(QRect(264, 341, 250, 21))
        sizePolicy.setHeightForWidth(self.camera_view_name_10.sizePolicy().hasHeightForWidth())
        self.camera_view_name_10.setSizePolicy(sizePolicy)
        self.camera_view_name_10.setMaximumSize(QSize(722, 37))
        self.camera_view_name_10.setFont(font3)
        self.camera_view_name_10.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_10.setMargin(0)
        self.camera_view_name_10.setIndent(15)
        self.camera_view_ai_check_11 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_11.setObjectName(u"camera_view_ai_check_11")
        self.camera_view_ai_check_11.setGeometry(QRect(740, 451, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_11.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_11.setSizePolicy(sizePolicy1)
        self.camera_view_ai_check_11.setFont(font1)
        self.camera_view_ai_check_11.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_11.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_11.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_11.setScaledContents(True)
        self.camera_view_ai_check_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_name_11 = QLabel(Ai_Setting_Window)
        self.camera_view_name_11.setObjectName(u"camera_view_name_11")
        self.camera_view_name_11.setGeometry(QRect(519, 341, 250, 20))
        sizePolicy.setHeightForWidth(self.camera_view_name_11.sizePolicy().hasHeightForWidth())
        self.camera_view_name_11.setSizePolicy(sizePolicy)
        self.camera_view_name_11.setMaximumSize(QSize(722, 37))
        self.camera_view_name_11.setFont(font3)
        self.camera_view_name_11.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_11.setMargin(0)
        self.camera_view_name_11.setIndent(15)
        self.camera_view_name_12 = QLabel(Ai_Setting_Window)
        self.camera_view_name_12.setObjectName(u"camera_view_name_12")
        self.camera_view_name_12.setGeometry(QRect(773, 341, 250, 20))
        sizePolicy.setHeightForWidth(self.camera_view_name_12.sizePolicy().hasHeightForWidth())
        self.camera_view_name_12.setSizePolicy(sizePolicy)
        self.camera_view_name_12.setMaximumSize(QSize(722, 37))
        self.camera_view_name_12.setFont(font3)
        self.camera_view_name_12.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_12.setMargin(0)
        self.camera_view_name_12.setIndent(15)
        self.camera_view_ai_check_12 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_12.setObjectName(u"camera_view_ai_check_12")
        self.camera_view_ai_check_12.setGeometry(QRect(993, 451, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_12.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_12.setSizePolicy(sizePolicy1)
        self.camera_view_ai_check_12.setFont(font1)
        self.camera_view_ai_check_12.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_12.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_12.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_12.setScaledContents(True)
        self.camera_view_ai_check_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_ai_check_13 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_13.setObjectName(u"camera_view_ai_check_13")
        self.camera_view_ai_check_13.setGeometry(QRect(228, 597, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_13.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_13.setSizePolicy(sizePolicy1)
        self.camera_view_ai_check_13.setFont(font1)
        self.camera_view_ai_check_13.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_13.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_13.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_13.setScaledContents(True)
        self.camera_view_ai_check_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_name_13 = QLabel(Ai_Setting_Window)
        self.camera_view_name_13.setObjectName(u"camera_view_name_13")
        self.camera_view_name_13.setGeometry(QRect(8, 487, 250, 20))
        sizePolicy.setHeightForWidth(self.camera_view_name_13.sizePolicy().hasHeightForWidth())
        self.camera_view_name_13.setSizePolicy(sizePolicy)
        self.camera_view_name_13.setMaximumSize(QSize(722, 37))
        self.camera_view_name_13.setFont(font3)
        self.camera_view_name_13.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_13.setMargin(0)
        self.camera_view_name_13.setIndent(15)
        self.camera_view_ai_check_14 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_14.setObjectName(u"camera_view_ai_check_14")
        self.camera_view_ai_check_14.setGeometry(QRect(485, 597, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_14.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_14.setSizePolicy(sizePolicy1)
        self.camera_view_ai_check_14.setFont(font1)
        self.camera_view_ai_check_14.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_14.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_14.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_14.setScaledContents(True)
        self.camera_view_ai_check_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_name_14 = QLabel(Ai_Setting_Window)
        self.camera_view_name_14.setObjectName(u"camera_view_name_14")
        self.camera_view_name_14.setGeometry(QRect(264, 487, 250, 20))
        sizePolicy.setHeightForWidth(self.camera_view_name_14.sizePolicy().hasHeightForWidth())
        self.camera_view_name_14.setSizePolicy(sizePolicy)
        self.camera_view_name_14.setMaximumSize(QSize(722, 37))
        self.camera_view_name_14.setFont(font3)
        self.camera_view_name_14.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_14.setMargin(0)
        self.camera_view_name_14.setIndent(15)
        self.camera_view_ai_check_15 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_15.setObjectName(u"camera_view_ai_check_15")
        self.camera_view_ai_check_15.setGeometry(QRect(739, 597, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_15.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_15.setSizePolicy(sizePolicy1)
        self.camera_view_ai_check_15.setFont(font1)
        self.camera_view_ai_check_15.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_15.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_15.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_15.setScaledContents(True)
        self.camera_view_ai_check_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.camera_view_name_15 = QLabel(Ai_Setting_Window)
        self.camera_view_name_15.setObjectName(u"camera_view_name_15")
        self.camera_view_name_15.setGeometry(QRect(519, 487, 250, 20))
        sizePolicy.setHeightForWidth(self.camera_view_name_15.sizePolicy().hasHeightForWidth())
        self.camera_view_name_15.setSizePolicy(sizePolicy)
        self.camera_view_name_15.setMaximumSize(QSize(722, 37))
        self.camera_view_name_15.setFont(font3)
        self.camera_view_name_15.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_15.setMargin(0)
        self.camera_view_name_15.setIndent(15)
        self.camera_view_name_16 = QLabel(Ai_Setting_Window)
        self.camera_view_name_16.setObjectName(u"camera_view_name_16")
        self.camera_view_name_16.setGeometry(QRect(773, 487, 250, 20))
        sizePolicy.setHeightForWidth(self.camera_view_name_16.sizePolicy().hasHeightForWidth())
        self.camera_view_name_16.setSizePolicy(sizePolicy)
        self.camera_view_name_16.setMaximumSize(QSize(722, 37))
        self.camera_view_name_16.setFont(font3)
        self.camera_view_name_16.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 170);")
        self.camera_view_name_16.setMargin(0)
        self.camera_view_name_16.setIndent(15)
        self.camera_view_ai_check_16 = QLabel(Ai_Setting_Window)
        self.camera_view_ai_check_16.setObjectName(u"camera_view_ai_check_16")
        self.camera_view_ai_check_16.setGeometry(QRect(994, 597, 24, 23))
        sizePolicy1.setHeightForWidth(self.camera_view_ai_check_16.sizePolicy().hasHeightForWidth())
        self.camera_view_ai_check_16.setSizePolicy(sizePolicy1)
        self.camera_view_ai_check_16.setFont(font1)
        self.camera_view_ai_check_16.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.camera_view_ai_check_16.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.camera_view_ai_check_16.setPixmap(QPixmap(u":/newPrefix/images/ai_on.png"))
        self.camera_view_ai_check_16.setScaledContents(True)
        self.camera_view_ai_check_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.all_select_bnt = QPushButton(Ai_Setting_Window)
        self.all_select_bnt.setObjectName(u"all_select_bnt")
        self.all_select_bnt.setGeometry(QRect(210, 7, 71, 33))
        self.all_select_bnt.setMinimumSize(QSize(17, 25))
        font5 = QFont()
        font5.setFamilies([u"NanumBarunGothic"])
        font5.setPointSize(11)
        self.all_select_bnt.setFont(font5)
        self.all_select_bnt.setCursor(QCursor(Qt.PointingHandCursor))
        self.all_select_bnt.setStyleSheet(u"background-color: rgb(36, 39, 44);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 13px;\n"
"border: 1px solid rgba(255, 255, 255, 100);\n"
"\n"
"\n"
"")
        self.ai_setting_info_label.raise_()
        self.camera_view_15.raise_()
        self.camera_view_1.raise_()
        self.camera_view_6.raise_()
        self.camera_view_14.raise_()
        self.camera_view_13.raise_()
        self.camera_view_8.raise_()
        self.camera_view_16.raise_()
        self.camera_view_11.raise_()
        self.camera_view_4.raise_()
        self.camera_view_3.raise_()
        self.camera_view_5.raise_()
        self.camera_view_2.raise_()
        self.camera_view_9.raise_()
        self.camera_view_7.raise_()
        self.camera_view_10.raise_()
        self.camera_view_12.raise_()
        self.close_bnt.raise_()
        self.camera_save_bnt.raise_()
        self.camera_view_ai_check_10.raise_()
        self.camera_view_ai_check_9.raise_()
        self.camera_view_ai_check_4.raise_()
        self.camera_view_ai_check_2.raise_()
        self.camera_view_ai_check_8.raise_()
        self.camera_view_ai_check_12.raise_()
        self.camera_view_ai_check_11.raise_()
        self.camera_view_ai_check_16.raise_()
        self.camera_view_ai_check_13.raise_()
        self.camera_view_ai_check_6.raise_()
        self.camera_view_ai_check_15.raise_()
        self.camera_view_ai_check_7.raise_()
        self.camera_view_ai_check_5.raise_()
        self.camera_view_ai_check_1.raise_()
        self.camera_view_ai_check_3.raise_()
        self.camera_view_ai_check_14.raise_()
        self.camera_view_name_4.raise_()
        self.camera_view_name_6.raise_()
        self.camera_view_name_7.raise_()
        self.camera_view_name_3.raise_()
        self.camera_view_name_5.raise_()
        self.camera_view_name_13.raise_()
        self.camera_view_name_15.raise_()
        self.camera_view_name_14.raise_()
        self.camera_view_name_12.raise_()
        self.camera_view_name_8.raise_()
        self.camera_view_name_9.raise_()
        self.camera_view_name_1.raise_()
        self.camera_view_name_2.raise_()
        self.camera_view_name_10.raise_()
        self.camera_view_name_11.raise_()
        self.camera_view_name_16.raise_()
        self.all_select_bnt.raise_()

        self.retranslateUi(Ai_Setting_Window)

        QMetaObject.connectSlotsByName(Ai_Setting_Window)
    # setupUi

    def retranslateUi(self, Ai_Setting_Window):
        self.ai_setting_info_label.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uc9c0\ub2a5\ud615 \ubd84\uc11d \uce74\uba54\ub77c \uc124\uc815", None))
        self.camera_view_15.setText("")
        self.camera_view_1.setText("")
        self.camera_view_6.setText("")
        self.camera_view_14.setText("")
        self.camera_view_13.setText("")
        self.camera_view_8.setText("")
        self.camera_view_16.setText("")
        self.camera_view_11.setText("")
        self.camera_view_4.setText("")
        self.camera_view_3.setText("")
        self.camera_view_5.setText("")
        self.camera_view_2.setText("")
        self.camera_view_9.setText("")
        self.camera_view_7.setText("")
        self.camera_view_10.setText("")
        self.camera_view_12.setText("")
        self.close_bnt.setText(QCoreApplication.translate("Ai_Setting_Window", u"\ucde8\uc18c", None))
        self.camera_save_bnt.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uc2e4\ud589", None))
        self.camera_view_ai_check_1.setText("")
        self.camera_view_name_1.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c1", None))
        self.camera_view_ai_check_2.setText("")
        self.camera_view_name_2.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c2", None))
        self.camera_view_ai_check_3.setText("")
        self.camera_view_name_3.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c3", None))
        self.camera_view_ai_check_4.setText("")
        self.camera_view_name_4.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c4", None))
        self.camera_view_ai_check_5.setText("")
        self.camera_view_name_5.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c5", None))
        self.camera_view_ai_check_6.setText("")
        self.camera_view_name_6.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c6", None))
        self.camera_view_ai_check_7.setText("")
        self.camera_view_name_7.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c7", None))
        self.camera_view_ai_check_8.setText("")
        self.camera_view_name_8.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c8", None))
        self.camera_view_ai_check_9.setText("")
        self.camera_view_name_9.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c9", None))
        self.camera_view_ai_check_10.setText("")
        self.camera_view_name_10.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c10", None))
        self.camera_view_ai_check_11.setText("")
        self.camera_view_name_11.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c11", None))
        self.camera_view_name_12.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c12", None))
        self.camera_view_ai_check_12.setText("")
        self.camera_view_ai_check_13.setText("")
        self.camera_view_name_13.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c13", None))
        self.camera_view_ai_check_14.setText("")
        self.camera_view_name_14.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c14", None))
        self.camera_view_ai_check_15.setText("")
        self.camera_view_name_15.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c15", None))
        self.camera_view_name_16.setText(QCoreApplication.translate("Ai_Setting_Window", u"\uce74\uba54\ub77c16", None))
        self.camera_view_ai_check_16.setText("")
        self.all_select_bnt.setText(QCoreApplication.translate("Ai_Setting_Window", u"\ubaa8\ub450 \uc120\ud0dd", None))
        pass
    # retranslateUi

