# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'login.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QWidget)
import ms_ai_img_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1270, 650)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QSize(1270, 650))
        Dialog.setMaximumSize(QSize(1270, 650))
        icon = QIcon()
        icon.addFile(u":/newPrefix/images/icon2.png", QSize(), QIcon.Normal, QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.background = QLabel(Dialog)
        self.background.setObjectName(u"background")
        self.background.setEnabled(True)
        self.background.setGeometry(QRect(0, 0, 1920, 1080))
        self.background.setPixmap(QPixmap(u":/newPrefix/images/main_bg2.jpg"))
        self.background.setAlignment(Qt.AlignmentFlag.AlignJustify|Qt.AlignmentFlag.AlignVCenter)
        self.background.setWordWrap(False)
        self.frame = QFrame(Dialog)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 1270, 650))
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QSize(0, 0))
        self.frame.setMaximumSize(QSize(1270, 650))
        self.frame.setStyleSheet(u"background-color: rgba(0, 0, 0, 109);")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.login_frame = QFrame(self.frame)
        self.login_frame.setObjectName(u"login_frame")
        self.login_frame.setGeometry(QRect(360, 130, 550, 400))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(5)
        sizePolicy1.setVerticalStretch(5)
        sizePolicy1.setHeightForWidth(self.login_frame.sizePolicy().hasHeightForWidth())
        self.login_frame.setSizePolicy(sizePolicy1)
        self.login_frame.setMinimumSize(QSize(550, 400))
        self.login_frame.setMaximumSize(QSize(550, 400))
        self.login_frame.setStyleSheet(u"background-color: rgb(13, 16, 23);\n"
"border-radius: 20px")
        self.login_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.login_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.id_icon = QLabel(self.login_frame)
        self.id_icon.setObjectName(u"id_icon")
        self.id_icon.setGeometry(QRect(110, 170, 31, 31))
        self.id_icon.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.id_icon.setPixmap(QPixmap(u"../../../../../home/microsystems-yang/.designer/MS-AI/FRONT/HTML/images/id.svg"))
        self.id_icon.setScaledContents(True)
        self.id_input = QLineEdit(self.login_frame)
        self.id_input.setObjectName(u"id_input")
        self.id_input.setGeometry(QRect(110, 180, 380, 25))
        self.id_input.setStyleSheet(u"font-size:11pt;\n"
"color: rgb(255, 255, 255);")
        self.pw_icon = QLabel(self.login_frame)
        self.pw_icon.setObjectName(u"pw_icon")
        self.pw_icon.setGeometry(QRect(110, 260, 31, 31))
        self.pw_icon.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.pw_icon.setPixmap(QPixmap(u"../../../../../home/microsystems-yang/.designer/MS-AI/FRONT/HTML/images/PW00.svg"))
        self.pw_icon.setScaledContents(True)
        self.pw_input = QLineEdit(self.login_frame)
        self.pw_input.setObjectName(u"pw_input")
        self.pw_input.setGeometry(QRect(110, 270, 380, 25))
        self.pw_input.setStyleSheet(u"font-size:14pt;\n"
"color: rgb(255, 255, 255);")
        self.pw_input.setEchoMode(QLineEdit.EchoMode.Password)
        self.pw_input.setCursorPosition(0)
        self.login_bn = QPushButton(self.login_frame)
        self.login_bn.setObjectName(u"login_bn")
        self.login_bn.setGeometry(QRect(50, 330, 461, 45))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(1)
        sizePolicy2.setVerticalStretch(1)
        sizePolicy2.setHeightForWidth(self.login_bn.sizePolicy().hasHeightForWidth())
        self.login_bn.setSizePolicy(sizePolicy2)
        font = QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.login_bn.setFont(font)
        self.login_bn.setStyleSheet(u"background-color: rgb(37, 40, 44);\n"
"border-radius: 10px;\n"
"color: rgb(252, 252, 252);")
        self.id_line = QFrame(self.login_frame)
        self.id_line.setObjectName(u"id_line")
        self.id_line.setGeometry(QRect(110, 210, 391, 1))
        font1 = QFont()
        font1.setPointSize(5)
        font1.setStrikeOut(False)
        self.id_line.setFont(font1)
        self.id_line.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.id_line.setAutoFillBackground(False)
        self.id_line.setStyleSheet(u"background-color: rgb(36, 39, 44)")
        self.id_line.setFrameShape(QFrame.Shape.HLine)
        self.id_line.setFrameShadow(QFrame.Shadow.Sunken)
        self.pw_line = QFrame(self.login_frame)
        self.pw_line.setObjectName(u"pw_line")
        self.pw_line.setGeometry(QRect(108, 299, 391, 1))
        self.pw_line.setFont(font1)
        self.pw_line.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.pw_line.setAutoFillBackground(False)
        self.pw_line.setStyleSheet(u"background-color: rgb(36, 39, 44)")
        self.pw_line.setFrameShape(QFrame.Shape.HLine)
        self.pw_line.setFrameShadow(QFrame.Shadow.Sunken)
        self.logo = QLabel(self.login_frame)
        self.logo.setObjectName(u"logo")
        self.logo.setGeometry(QRect(160, 40, 251, 41))
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy3)
        self.logo.setPixmap(QPixmap(u":/newPrefix/images/logo.png"))
        self.logo.setScaledContents(True)
        self.label = QLabel(self.login_frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(110, 148, 91, 31))
        font2 = QFont()
        font2.setPointSize(12)
        self.label.setFont(font2)
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_2 = QLabel(self.login_frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(110, 240, 91, 31))
        self.label_2.setFont(font2)
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.id_icon.raise_()
        self.id_input.raise_()
        self.pw_input.raise_()
        self.login_bn.raise_()
        self.id_line.raise_()
        self.pw_line.raise_()
        self.pw_icon.raise_()
        self.logo.raise_()
        self.label.raise_()
        self.label_2.raise_()
        QWidget.setTabOrder(self.id_input, self.pw_input)
        QWidget.setTabOrder(self.pw_input, self.login_bn)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"login", None))
        self.background.setText("")
        self.id_icon.setText("")
        self.id_input.setText("")
        self.pw_icon.setText("")
        self.pw_input.setText("")
        self.login_bn.setText(QCoreApplication.translate("Dialog", u"\ub85c\uadf8\uc778", None))
        self.logo.setText("")
        self.label.setText(QCoreApplication.translate("Dialog", u"\uc544\uc774\ub514", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"\ube44\ubc00\ubc88\ud638", None))
    # retranslateUi

